services:
  
  #php-fpm server
  php:
    container_name: php-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    ports:
      - 9000:9000
    depends_on:
      - database

  # nginx server
  web:
    container_name: nginx-server
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 9090:8080
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel
    depends_on:
      - php

  # database server
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
volumes:
  db-data: ~